name: environment_visualitzacio
channels:
- conda-forge
dependencies:
- jupyter=1.1.1
- matplotlib=3.10.6
- numpy=2.3.3
- pandas=2.3.3
- pip
- python=3.12
- scikit-learn==1.7.2
- scipy==1.16.2
- openpyxl==3.1.5
- geopandas==0.14.1
- scikit-learn==1.7.2